// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8smHR1i20yyCMikTYsQBt0HkAF0Tab8',
    appId: '1:692767944401:web:d02510d28570e8ec97dff0',
    messagingSenderId: '692767944401',
    projectId: 'transfusion-c725d',
    authDomain: 'transfusion-c725d.firebaseapp.com',
    storageBucket: 'transfusion-c725d.firebasestorage.app',
    measurementId: 'G-7SX802ENY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwVFkyoUJV_qdpPG_etqU8KiJ9BYBkEvw',
    appId: '1:692767944401:android:183099f5dd1226cd97dff0',
    messagingSenderId: '692767944401',
    projectId: 'transfusion-c725d',
    storageBucket: 'transfusion-c725d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGRvWgiJ5CsBra1OawWB7avNREDMXiBI',
    appId: '1:692767944401:ios:31f30a4b7f5fdb1797dff0',
    messagingSenderId: '692767944401',
    projectId: 'transfusion-c725d',
    storageBucket: 'transfusion-c725d.firebasestorage.app',
    iosClientId: '692767944401-o9r27jv7ck46o5v21fuhoq1i9jsset4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.transfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGRvWgiJ5CsBra1OawWB7avNREDMXiBI',
    appId: '1:692767944401:ios:31f30a4b7f5fdb1797dff0',
    messagingSenderId: '692767944401',
    projectId: 'transfusion-c725d',
    storageBucket: 'transfusion-c725d.firebasestorage.app',
    iosClientId: '692767944401-o9r27jv7ck46o5v21fuhoq1i9jsset4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.transfusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR8smHR1i20yyCMikTYsQBt0HkAF0Tab8',
    appId: '1:692767944401:web:e7574343c047a24e97dff0',
    messagingSenderId: '692767944401',
    projectId: 'transfusion-c725d',
    authDomain: 'transfusion-c725d.firebaseapp.com',
    storageBucket: 'transfusion-c725d.firebasestorage.app',
    measurementId: 'G-8TV2JX5G8J',
  );
}
