import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
// Note: firebase_options.dart will be generated by flutterfire configure
import 'firebase_options.dart';

import 'core/theme.dart';
import 'providers/mtp_state_provider.dart';
import 'providers/admin_settings_provider.dart';
import 'services/auth_service.dart';
import 'screens/auth_wrapper.dart';
import 'screens/splash_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/admin_screen.dart';
import 'screens/assessment_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/end_case_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
        ChangeNotifierProvider(create: (_) => MtpStateProvider()),
        ChangeNotifierProvider(create: (_) => AdminSettingsProvider()),
      ],
      child: const TransfusionMTPApp(),
    ),
  );
}

class TransfusionMTPApp extends StatelessWidget {
  const TransfusionMTPApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MTP Protocol',
      theme: AppTheme.darkTheme,
      debugShowCheckedModeBanner: false,
      initialRoute: '/auth',
      routes: {
        '/auth': (context) => const AuthWrapper(),
        '/splash': (context) => const SplashScreen(),
        '/profile': (context) => const ProfileScreen(),
        '/admin': (context) => const AdminScreen(),
        '/assessment': (context) => const PatientAssessmentScreen(),
        '/dashboard': (context) => const ActiveMTPScreen(),
        '/summary': (context) => const EndCaseScreen(),
      },
    );
  }
}
